
export function login(userToLogin) {
    return async dispatch => {
        try {
        } catch (err) {
            console.log('error in login function userAction', err)
        }
    }
}
